/**
 * Persistence helpers for workflow execution tracking.
 *
 * Async wrappers around PrismaClient — no business logic here.
 * Every state transition during execution gets recorded so the
 * run history is fully auditable.
 *
 * Design notes (v2 — Prisma):
 * - All functions are now async (Prisma is async-only).
 * - JSON payloads are stored as TEXT via JSON.stringify.
 * - IDs are generated by Prisma cuid().
 * - Output JSON > 100KB is truncated to prevent SQLite bloat.
 */
import prisma from "../db/client";
import type { RunStatus, StepStatus, EventType } from "./types";

const MAX_OUTPUT_BYTES = 100 * 1024; // 100 KB

/**
 * Safely stringify and optionally truncate a JSON payload.
 */
function safeStringify(value: unknown): string {
  const raw = JSON.stringify(value);
  if (raw.length > MAX_OUTPUT_BYTES) {
    const truncated = raw.slice(0, MAX_OUTPUT_BYTES);
    return JSON.stringify({ _truncated: true, _preview: truncated });
  }
  return raw;
}

// ── Row type interfaces (for external consumers) ────────────────────

export interface WorkflowRow {
  id: string;
  name: string;
  schema_json: string;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface WorkflowRunRow {
  id: string;
  workflow_id: string;
  status: string;
  input_json: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

/** Extended run row that includes the workflow name (for list views). */
export interface WorkflowRunWithName extends WorkflowRunRow {
  workflow_name: string;
}

export interface RunStepRow {
  id: string;
  run_id: string;
  node_id: string;
  status: string;
  input_json: string | null;
  output_json: string | null;
  error_message: string | null;
  error_stack: string | null;
  agent_session_id: string | null;
  started_at: string;
  completed_at: string | null;
}

export interface RunEventRow {
  id: string;
  run_id: string;
  step_id: string | null;
  event_type: string;
  payload: string;
  created_at: string;
}

// ── Helpers to convert Prisma results to legacy row format ──────────

function toWorkflowRow(w: {
  id: string;
  name: string;
  schemaJson: string;
  version: number;
  createdAt: Date;
  updatedAt: Date;
}): WorkflowRow {
  return {
    id: w.id,
    name: w.name,
    schema_json: w.schemaJson,
    version: w.version,
    created_at: w.createdAt.toISOString(),
    updated_at: w.updatedAt.toISOString(),
  };
}

function toWorkflowRunRow(r: {
  id: string;
  workflowId: string;
  status: string;
  inputJson: string;
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
}): WorkflowRunRow {
  return {
    id: r.id,
    workflow_id: r.workflowId,
    status: r.status,
    input_json: r.inputJson,
    started_at: r.startedAt?.toISOString() ?? null,
    completed_at: r.completedAt?.toISOString() ?? null,
    created_at: r.createdAt.toISOString(),
  };
}

function toRunStepRow(s: {
  id: string;
  runId: string;
  nodeId: string;
  status: string;
  inputJson: string | null;
  outputJson: string | null;
  errorMessage: string | null;
  errorStack: string | null;
  agentSessionId: string | null;
  startedAt: Date;
  completedAt: Date | null;
}): RunStepRow {
  return {
    id: s.id,
    run_id: s.runId,
    node_id: s.nodeId,
    status: s.status,
    input_json: s.inputJson,
    output_json: s.outputJson,
    error_message: s.errorMessage,
    error_stack: s.errorStack,
    agent_session_id: s.agentSessionId,
    started_at: s.startedAt.toISOString(),
    completed_at: s.completedAt?.toISOString() ?? null,
  };
}

function toRunEventRow(e: {
  id: string;
  runId: string;
  stepId: string | null;
  eventType: string;
  payload: string;
  createdAt: Date;
}): RunEventRow {
  return {
    id: e.id,
    run_id: e.runId,
    step_id: e.stepId,
    event_type: e.eventType,
    payload: e.payload,
    created_at: e.createdAt.toISOString(),
  };
}

// ── Step lifecycle ──────────────────────────────────────────────────

/**
 * Create a RunStep record with status='running'.
 * @returns The new step's ID.
 */
export async function createRunStep(runId: string, nodeId: string): Promise<string> {
  const step = await prisma.runStep.create({
    data: { runId, nodeId, status: "running" },
  });
  return step.id;
}

/**
 * Mark a step as completed with its output JSON.
 */
export async function completeRunStep(stepId: string, outputs: unknown): Promise<void> {
  const outputJson = safeStringify(outputs);
  await prisma.runStep.update({
    where: { id: stepId },
    data: { status: "completed", outputJson, completedAt: new Date() },
  });
}

/**
 * Mark a step as failed with error details.
 */
export async function failRunStep(stepId: string, error: unknown): Promise<void> {
  const message = error instanceof Error ? error.message : String(error);
  const stack = error instanceof Error ? (error.stack ?? "") : "";
  await prisma.runStep.update({
    where: { id: stepId },
    data: {
      status: "failed",
      errorMessage: message,
      errorStack: stack,
      completedAt: new Date(),
    },
  });
}

/**
 * Store the agent session ID on a step (for agent nodes).
 */
export async function setStepAgentSession(stepId: string, sessionId: string): Promise<void> {
  await prisma.runStep.update({
    where: { id: stepId },
    data: { agentSessionId: sessionId },
  });
}

// ── Event logging ───────────────────────────────────────────────────

/**
 * Insert a RunEvent (audit trail entry).
 * @param stepId - May be null for run-level events (e.g. workflow_completed).
 */
export async function logEvent(
  runId: string,
  stepId: string | null,
  eventType: EventType,
  payload: unknown = {}
): Promise<void> {
  await prisma.runEvent.create({
    data: {
      runId,
      stepId,
      eventType,
      payload: safeStringify(payload),
    },
  });
}

// ── Run status ──────────────────────────────────────────────────────

/**
 * Update the status of a WorkflowRun.
 * Sets completedAt on terminal states (completed, failed).
 */
export async function updateRunStatus(runId: string, status: RunStatus): Promise<void> {
  const isTerminal = status === "completed" || status === "failed";
  const data: Record<string, unknown> = { status };

  if (status === "running") {
    data.startedAt = new Date();
  }
  if (isTerminal) {
    data.completedAt = new Date();
  }

  await prisma.workflowRun.update({
    where: { id: runId },
    data,
  });
}

// ── Workflow CRUD ───────────────────────────────────────────────────

/**
 * Create a new workflow definition.
 * @returns The created workflow's ID.
 */
export async function createWorkflow(
  id: string,
  name: string,
  schemaJson: string
): Promise<string> {
  const workflow = await prisma.workflow.create({
    data: { id, name, schemaJson, version: 1 },
  });
  return workflow.id;
}

/**
 * Find a workflow by ID.
 */
export async function getWorkflow(id: string): Promise<WorkflowRow | undefined> {
  const w = await prisma.workflow.findUnique({ where: { id } });
  return w ? toWorkflowRow(w) : undefined;
}

/**
 * List all workflows, newest first.
 */
export async function listWorkflows(): Promise<WorkflowRow[]> {
  const rows = await prisma.workflow.findMany({
    orderBy: { createdAt: "desc" },
  });
  return rows.map(toWorkflowRow);
}

// ── WorkflowRun CRUD ───────────────────────────────────────────────

/**
 * Create a new workflow run record.
 * @returns The new run's ID.
 */
export async function createWorkflowRun(
  workflowId: string,
  input: Record<string, unknown>
): Promise<string> {
  const run = await prisma.workflowRun.create({
    data: {
      workflowId,
      status: "pending",
      inputJson: JSON.stringify(input),
    },
  });
  return run.id;
}

/**
 * Get a workflow run by ID.
 */
export async function getWorkflowRun(id: string): Promise<WorkflowRunRow | undefined> {
  const r = await prisma.workflowRun.findUnique({ where: { id } });
  return r ? toWorkflowRunRow(r) : undefined;
}

/**
 * Get a workflow run by ID with all steps and events included.
 */
export async function getWorkflowRunWithDetails(id: string): Promise<{
  run: WorkflowRunRow & { workflow_name: string; schema_json: string };
  steps: RunStepRow[];
  events: RunEventRow[];
} | undefined> {
  const r = await prisma.workflowRun.findUnique({
    where: { id },
    include: {
      workflow: { select: { name: true, schemaJson: true } },
      steps: { orderBy: { startedAt: "asc" } },
      events: { orderBy: { createdAt: "asc" } },
    },
  });
  if (!r) return undefined;
  return {
    run: {
      ...toWorkflowRunRow(r),
      workflow_name: r.workflow.name,
      schema_json: r.workflow.schemaJson,
    },
    steps: r.steps.map(toRunStepRow),
    events: r.events.map(toRunEventRow),
  };
}

/**
 * List recent runs, newest first. Limited to 50 by default.
 * Includes the workflow name for each run (used by GET /runs list view).
 */
export async function listRuns(limit = 50): Promise<WorkflowRunWithName[]> {
  const rows = await prisma.workflowRun.findMany({
    orderBy: { createdAt: "desc" },
    take: limit,
    include: { workflow: { select: { name: true } } },
  });
  return rows.map((r) => ({
    ...toWorkflowRunRow(r),
    workflow_name: r.workflow.name,
  }));
}

/**
 * Get all runs for a workflow.
 */
export async function getRunsByWorkflowId(workflowId: string): Promise<WorkflowRunRow[]> {
  const rows = await prisma.workflowRun.findMany({
    where: { workflowId },
    orderBy: { createdAt: "desc" },
  });
  return rows.map(toWorkflowRunRow);
}

/**
 * Get all steps for a run.
 */
export async function getRunSteps(runId: string): Promise<RunStepRow[]> {
  const rows = await prisma.runStep.findMany({
    where: { runId },
    orderBy: { startedAt: "asc" },
  });
  return rows.map(toRunStepRow);
}

/**
 * Get all events for a run.
 */
export async function getRunEvents(runId: string): Promise<RunEventRow[]> {
  const rows = await prisma.runEvent.findMany({
    where: { runId },
    orderBy: { createdAt: "asc" },
  });
  return rows.map(toRunEventRow);
}

/**
 * Mark all "running" runs as failed — called on startup to recover
 * from unclean shutdowns.
 */
export async function markOrphanedRunsFailed(): Promise<number> {
  const result = await prisma.workflowRun.updateMany({
    where: { status: "running" },
    data: { status: "failed", completedAt: new Date() },
  });
  return result.count;
}
